name: "Sample CI test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  on-push-job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello world"

      - name: Print date
        run: date

  on-pull-job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: On pull test
        run: echo "Hello from on pull"

      - name: Print directory
        run: pwd

      - name: Print Directory
        run: ls
  
  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Workflwo dispatch Test"
        run: echo "from workflow dispatch"