name: "Sample CI test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello world"