name: "Sample CI test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  on-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello world"

      - name: Print date
        run: date

  on-pull-job:
    runs-on: ubuntu-latest
    steps:
      - name: On pull test
        run: echo "Hello from on pull"

      - name: Print directory
        run: pwd

      - name: Print Directory
        run: ls