name: Notify Test using CI

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo 'Hello World'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: echo 'Running Test...'

      - name: Suppose to Fail
        run: wtsg       # failing command

  notify:
    runs-on: ubuntu-latest
    needs: test     # this job depends on the test job
    if: failure()   # if previous job fails
    steps: 
      - name: Checking out
        uses: actions/checkout@v4

      - name: Check Directory list
        run: ls

      - name: Notify Developer
        run: |
          chmod +x ./notify_script.sh       # make sure executiong permission is given
          ./notify_script.sh                # should not be inside .github/workflow, it must be in repo

      - name: Confirmation
        run: echo "Notified"